version: 2
jobs:
  build:
    macos:
      xcode: "11.5"
    environment:
      OPAMYES: "1"
      OPAMJOBS: "2"
      MACOSX_DEPLOYMENT_TARGET: "10.15"
      CUSTOM_OPAM: "1"
      OPAM_REPO: repo/darwin
      OPAM_COMP: "4.07.0"
      OPAMVERBOSE: 1
      TERM: vt100
    steps:
      - checkout
      - run: brew install wget opam pkg-config autoconf dylibbundler
      - run: make
      - run: make artefacts
      - run: make test
      - store_artifacts:
          path: vpnkit.tgz
      - store_artifacts:
          path: COMMIT
      - store_artifacts:
          path: OSS-LICENSES
workflows:
  version: 2
  build-test-vpnkit:
    jobs:
      - build
